### ISSUE TITLE
Postfix : send mail from server and not from mandrill

### ISSUE THREAD

**Issue by YannickB** [clouder-community/clouder#10]
Hello world,

After a whole day spent to try to send the mails of the mailing list from my server (and so not from the currently used mandrill), I have to give up I'll not be able to do it alone.

This is a concern for me because the mailing list of Odoo, used by the mailing list of goclouder.net, send for each answer a mail to each people who subscribed. So if we have one hundred people on the mailing list, one hundred mail will be send for each answer.
I have a free fair use of 12000 with mandrill, but I'm afraid to quickly reach this number when I'll start to promote Clouder and then I'll have to pay for the mailing list. That's why I tried to configure my postfix to directly send mail but all my mails finish in spam (ip not blacklisted, SPF ok, couldn't make DKIM work)

I give up and wait until someone correct and use the clouder_template_postfix module to send his email directly, and make it work for the mailing list of Odoo. I think we still need to add SPF and DKIM in it, here is the tutorial I used (french) : 
https://www.skyminds.net/serveur-dedie-ajouter-lauthentification-spf-sender-id-et-dkim-a-postfix-et-bind9-avec-opendkim/

Also, until this is done, if someone has a working SMTP server I could connect with sasl to send the emails of the mailing list I'd greatly appreciate it.

**Comment by pierreozoux** [comment]
It is indeed a pain in the ~...

I recommend following this: it's better than tutorial, it's code used by thousands of people: https://github.com/mail-in-a-box/mailinabox

I used it to base my email image: https://github.com/IndiePaaS/IndiePaaS/tree/master/dockerfiles/email
I would be happy to collaborate on this one :)
If you need help on getting started let me know.

And yes, you definitely need DKIM working!

Best,

Pierre

**Comment by YannickB** [comment]
Thank you for the link pierre, it looks interesting indeed.

I have just one regret, I only wanted to have in the postfix container postfix, SPF, DKIM and everything needed to make sure sent email don't go to spam, but I want webmail, DNS and owncloud on another container to keep the infrastructure granular enough.
That said, what can do more can do less, so it may be a good approach.

I started the promotion around Clouder so I have no more time to do it myself, but theses informations will stay here until someone take care of it.

**Comment by pierreozoux** [comment]
Yes, agreed, that's why I did my own version (I also need multi domain management).

We have to find a way to work on the same images :) Let's see in May during the OuiShare Labs :)

**Comment by YannickB** [comment]
Closing all old tickets, SPF and DKIM were added meanwhile.
