### ISSUE TITLE
api decorator in templates

### ISSUE THREAD

**Issue by amon-ra** [clouder-community/clouder#102]
I have been working in your platform and I saw that in templates you are using api.multi decorator when it should be api.one decorator. Is this ok or am I wrong? 

Example:
```
    @api.multi
    def deploy_post(self):
        super(ClouderContainer, self).deploy_post()

        if self.application_id.type_id.name == 'wordpress':
            self.execute(
                         ['wget', '-q', 'https://wordpress.org/latest.tar.gz',
                          'latest.tar.gz'], path='/var/www/', username='www-data')
```

**Comment by YannickB** [comment]
Hum from what I know @api.multi is the default decorator to use, @api.one is reserved to very specific case (like constraints for example).

**Comment by amon-ra** [comment]
@api.multi returns a recordset and @api.one returns a record. In this case the function is normaly called on only one object but if it used in a list on interface it could produce an error. 
This is what I understand in documentation.
In odoo 9 @api.one is deprecated and the recomended use is @api.multi and iterate on records, and using self.ensure_one()
Ref: https://www.odoo.com/documentation/8.0/reference/orm.html

Thanks. I close the issue
