### ISSUE TITLE
Error in models.py execute function

### ISSUE THREAD

**Issue by amon-ra** [clouder-community/clouder#103]
When I call execute function in Model class with stdin_arg parameters, I have an error in parser

```
        # Pushing additional input
        if stdin_arg:
            chnl_stdin = channel.makefile('wb', -1)
            for arg in chnl_stdin:
                self.log('command : ' + arg)
                chnl_stdin.write(arg)
                chnl_stdin.flush()
```
I think it should be:
```
        # Pushing additional input
        if stdin_arg:
            chnl_stdin = channel.makefile('wb', -1)
            for arg in stdin_arg:
                self.log('command : ' + arg)
                chnl_stdin.write(arg)
                chnl_stdin.flush()
```

It is ok?

**Comment by nicolas-petit** [comment]
I think the change you propose is correct.


Just to make sure:
Did you try the fix you're proposing ?
If it works do the logs show the commands correctly with all the arguments ?

If so then I believe your new code is OK.

**Comment by amon-ra** [comment]
For me it is working ok

**Comment by YannickB** [comment]
Ok I merged the fix, thanks for the report

**Comment by amon-ra** [comment]
Sorry I miss that you need -i parameter to docker exec
