### ISSUE TITLE
identityfile is a list if paramiko >= 1.10.0

### ISSUE THREAD

**Issue by hhgabelgaard** [clouder-community/clouder#11]
I'm getting this error on save of Containers

    File "/opt/odoo/clouder/clouder/clouder_model.py", line 391, in connect
        + ", type : " + type(identityfile)))
    TypeError: cannot concatenate 'str' and 'type' objects

This is easily fixed by adding a `str()`:
```python
    if not isinstance(identityfile, basestring):
                raise except_orm(
                    _('Data error!'),
                    _("For unknown reason, it seems the variable identityfile in "
                      "the connect ssh function is invalid. Please report "
                      "this message.\n"
                      "Identityfile : " + str(identityfile)
                      + ", type : " + str(type(identityfile))))
```
Which then reveals the real problem:

    Data error!
    
    For unknown reason, it seems the variable identityfile in the connect ssh function is invalid. Please report this message.
    Identityfile : ['/opt/odoo/.ssh/keys/clouder1.xxxx.yyy'], type : <type 'list'>

The config file seems rigth:

    Host clouder1.xxxx.yyy
      HostName clouder1.xxxx.yyy
      Port 14022
      User root
      IdentityFile /opt/odoo/.ssh/keys/clouder1.xxxx.yyy
    #END clouder1.xxxx.yyy

So why is identityfile a list, and not a string?

This is on Ubuntu 14.04, Python 2.7.6, paramiko==1.15.2

Found this on Paramiko 1.10.0 2013-03-01 release notes:

[Feature] #93: Overhaul SSH config parsing to be in line with man ssh_config (& the behavior of ssh itself), including addition of parameter expansion within config values. 

For example, the IdentityFile change turns config objects' identityfile key values into lists when they were strings before, so code expecting a string in that slot (e.g. parts of Fabric, though that is only one client-usage example) will break.

https://github.com/paramiko/paramiko/pull/93

This can be solved by 
```python
if isinstance(identityfile, list ):
            identityfile = identityfile[0]
```

Now I can save some Containers. The Backup Bup gives me an connect error from `deploy_link()`:

      File "/opt/odoo/clouder/clouder/clouder_template_backup/clouder_template_backup.py", line 66,   in deploy_link
         username='backup')
       File "/opt/odoo/odoo8/openerp/api.py", line 239, in wrapper
         return new_api(self, *args, **kwargs)
       File "/opt/odoo/clouder/clouder/clouder_model.py", line 408, in connect
         "Error : " + str(inst)))
     except_orm: (u'Connect error!', u"We were not able to connect to your server. Please make sure   you add the public key in the authorized_keys file of your root user on your server.\nIf you were trying to connect to a container, a click on the 'reset key' button on the container record may resolve the  problem.\nError : [Errno 111] Connection refused")

But I think I would leave that to a new issue, when I have looked more into the problem.

Thanks for your time and for a great project
hhg

**Comment by YannickB** [comment]
Thank you, I don't know if you saw the discussion in the mailing list about this bug, I was about to fix it with the exact same code.

You gave us a good insight of the reason of the bug. I used only Debian on my own infrastructure and it seems most of the newcomers use Ubuntu, the problem come from the version of paramiko, makes sense.

Thank you for this deep analysis, it will serve as reference.

Regarding your connection problem, can you check if you can connect from your Clouder system user? Sometimes after deploying a container it try to connect a little too fast, before the ssh daemon is up (reason for the time.sleep line 692 of https://github.com/clouder-community/clouder/blob/8.0/clouder/clouder_container.py). Don't hesitate to reopen the issue if you need.
