### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by DouaeAhmadoun** [clouder-community/clouder#115]
Following the installation guide provided by the documentation, I'm asked to build some images.
Yet, some images are missing in my configuration.
The missing images are :  img_archive and img_odoo.

What should I do please?

**Comment by YannickB** [comment]
Hello,

Unfortunately the documentation is outdated, until it's updated if it's your first deployment I suggest either you use the oneclick installer in server object, or follow its process manually : 
https://github.com/clouder-community/clouder/blob/8.1/clouder_template_odoo/oneclick.py
Every command here can be done directly on the interface.

**Comment by DouaeAhmadoun** [comment]
Hello,

It's solved, thank you Yannick.
