### ISSUE TITLE
LDAP and SSO

### ISSUE THREAD

**Issue by YannickB** [clouder-community/clouder#15]
Hello everyone,

I'd like to give you the vision I have regarding the uses cases of Clouder, from a professional hosters perspective.

A professional hosters will want to manage the following case : 
-Create containers for each of his customers (mono customer container)
-Create bases for each of his customers (mono customer base)
-Create one or several container or base, and then give access to some of them to their customers (multi customer container/base). Imagine for example a seafile application with one hundred customer using it, each having 25Go available for them.

We can easily manage the first two case today, but the later will be more difficult. Here is how I see it : 
The customer will go on the hoster website and buy the access
The customer info is stored into Clouder and exported into an LDAP which is accessible by the applications.
The applications often have an LDAP module we can use. We use ldap tag or group to know which customer should access to which application.
We use an SSO system (CAS?) so the customer only have to login one time to access to all of his applications.

I want it to be as easy to use as google services, you buy your access, you login once and then you can access to all your application which are linked between them. This is the ultimate goal of Clouder, making so everyone can easily deploy an hosting infrastructure as easy to use as Google, but fully based on open-source applications.

So as you understood, we need to have an ldap and and sso container. I propose openldap and CAS, and I already started to develop some modules with them but I quickly understood it was out of my league, so I'll need your help to prepare theses very important containers.

**Comment by pasgou** [comment]
Good Vision
The vision I have with an odoo perspective is having the two choices between : 
- Or having a global access for all client with client.mydomain.tld
- Or having his own access with www.client.tld
All of this, with clouder, will be possible and your work is welcome.
Thanks.

**Comment by YannickB** [comment]
This feature is still important and I hope we will adress it shortly. I am closing all tickets about features we are not working on currently.
