### ISSUE TITLE
Activate CodeCov

### ISSUE THREAD

**Issue by lasley** [clouder-community/clouder#155]
Hi @YannickB - Can you please sign up for [CodeCov](https://codecov.io/) & give it permissions to this repo? This will work seamlessly with OCA MQT in order to provide us test coverage results. [Coveralls](coveralls.io) is supported to, if you would prefer that (or both)

**Comment by YannickB** [comment]
@lasley ok it's done : https://codecov.io/gh/clouder-community/clouder, please let me know if I forgot to do something. If you quoted CodeCov first I guess it's with good reason so let's stick with that.

Still wondering how we will write unit test here

**Comment by lasley** [comment]
Woot thanks @YannickB - yeah CodeCov is more accurate with the PR diffs.

I setup a test base in my SSH environment PR, and will begin steadily building that out for us and testing core in order to show how it's done. The high level is just heavy and creative use of mocks.
