### ISSUE TITLE
[RFC] Messaging System

### ISSUE THREAD

**Issue by lasley** [clouder-community/clouder#190]
This isn't really a current goal, but it is something I'd like as part of the system and I think it'll make good training wheels as @t3ddftw's first Clouder Template.

The system I've been looking at is [Mattermost](https://about.mattermost.com), but the SAML is Enterprise only.

Another one that I have been looking at, which does have LDAP as part of the community offering, is [Rocket Chat](https://rocket.chat/). 

Any thoughts, or other things we should explore?

**Comment by YannickB** [comment]
Totally agree, mattermost is already on the todo list. I think I already saw rocket chat too, but I don't remember the added value with mattermost.

**Comment by lasley** [comment]
I was totally on board until I figured out that Mattermost Enterprise was the only one that supports LDAP. I'm going to look more to see if I can figure out the featureset it contains that RocketChat doesn't. Let me know if you remember anything on that 😄

**Comment by YannickB** [comment]
I guessed something like this. IMO we still should chose the more advanced software regardless of LDAP support, as I said often the best open core softwares will have closed LDAP features but I'm willing to bet that the very existence of Clouder will in the long run either force to open-source the LDAP connector or develop community module/hack which will implement it.

So regarding Mattermost vs Rocketchat, we should do a point to point comparison and not really take LDAP support into account.

**Comment by lasley** [comment]
That's the thing - I did a few point-by-points and wasn't able to identify a difference between the applications outside of the LDAP support.

I do like the stack that Mattermost is built on better - React and Golang, but in terms of the actual features I am having trouble finding any functional difference. The mattermost app looks a bit better maybe.

**Comment by YannickB** [comment]
Interesting feedback : http://www.akitaonrails.com/2016/08/13/choosing-mattermost-over-rocket-chat-and-slack

For now my vote is still on mattermost, I feel it's more mature and has probably better user experience (the most important point IMO), but rocketchat is not far.

**Comment by lasley** [comment]
Nice, I'll read this article thanks.

What's our solution for SSO if we go the Mattermost direction?

**Comment by YannickB** [comment]
The solution will probably be account creation in mattermost database/API, executed by Clouder. We shall first make the LDAP template I think, then we'll figure something. 
Lack of LDAP support will happen way too often, we can completely rely on it even if we should use it when we can.
