### ISSUE TITLE
Postgres image does not include bash

### ISSUE THREAD

**Issue by amon-ra** [clouder-community/clouder#201]
I am testing master branch and for example gitlab template is trying to execute creation scripts using bash that is missing in postgres container.

I have installed it locally but it is a temporal workaround.

**Comment by YannickB** [comment]
In master for now you shall test only the applications which are deployed in the oneclick action (launched in node form). 

Still I added bash in postgres, it is not included by defaults because the postgres image does not inherit the clouder base image.
