### ISSUE TITLE
Error - adding server

### ISSUE THREAD

**Issue by ygol** [clouder-community/clouder#21]
on adding 1st server, 
odoo throw the following error when saving the form. the path to the ssh keys seems wrong.

any idea? TIA

===================
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/addons/yannick/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/yannick/clouder_template_shinken/clouder_template_shinken.py", line 46, in deploy
    super(ClouderServer, self).deploy()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/yannick/clouder/clouder_container.py", line 182, in deploy
    self.execute_write_file(key_file, self.private_key)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/yannick/clouder/clouder_model.py", line 539, in execute_write_file
    f = open(localfile, 'a')
IOError: [Errno 2] No such file or directory: u'/opt/odoo/.ssh/keys/ns30.eu'

**Comment by caiuka** [comment]
The directory "/opt/odoo/.ssh/keys” need to exist. Usually you just need to create the "keys” folder, so you should resolve with a simple “mkdir /opt/odoo/.ssh/keys"


Gianluca Milano / business integrator 
+39 335 6010512 / gm@gianlucamilano.com <mailto:gm@gianlucamilano.com>
gianlucamilano 
Office: +39 081 19465159 / Fax: +39 081 19465159 
Via Trepiccioni, 39 - 80078 Pozzuoli (NA) - ITALY 
http://www.gianlucamilano.com <http://www.gianlucamilano.com/>

 <https://twitter.com/gianluca_milano>  <https://twitter.com/gianluca_milano> <https://www.google.com/+GianlucaMilanoIng>  <https://www.google.com/+GianlucaMilanoIng> <https://it.linkedin.com/in/gianlucamilano/>  <https://it.linkedin.com/in/gianlucamilano/> <skype:ing.gianlucamilano?chat>


 <skype:ing.gianlucamilano?chat>
This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company. <skype:ing.gianlucamilano?chat>
> Il giorno 18/mag/2015, alle ore 09:05, Yves Goldberg <notifications@github.com> ha scritto:
> 
> /opt/odoo/.ssh/keys

**Comment by ygol** [comment]
thank you Luca. it did indeed solve the problem but wouldn't the native .ssh directory (~/.ssh/) should be used?

And if "/opt/odoo/.ssh/keys" must exist; did you manually created the directory when you installed clouder?

**Comment by caiuka** [comment]
Ciao Yves,

about using the directory keys to store the different private keys, I guess it’s a matter of design, to have a better order.

Yes, I created it manually, as I’ve had the same error you reported.


Gianluca Milano / business integrator 
+39 335 6010512 / gm@gianlucamilano.com <mailto:gm@gianlucamilano.com>
gianlucamilano 
Office: +39 081 19465159 / Fax: +39 081 19465159 
Via Trepiccioni, 39 - 80078 Pozzuoli (NA) - ITALY 
http://www.gianlucamilano.com <http://www.gianlucamilano.com/>

 <https://twitter.com/gianluca_milano>  <https://twitter.com/gianluca_milano> <https://www.google.com/+GianlucaMilanoIng>  <https://www.google.com/+GianlucaMilanoIng> <https://it.linkedin.com/in/gianlucamilano/>  <https://it.linkedin.com/in/gianlucamilano/> <skype:ing.gianlucamilano?chat>


 <skype:ing.gianlucamilano?chat>
This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company. <skype:ing.gianlucamilano?chat>

**Comment by YannickB** [comment]
Good catch, see commit linked we shall not have the problem anymore

**Comment by YannickB** [comment]
Can we close this ticket?
