### ISSUE TITLE
problem in application_type

### ISSUE THREAD

**Issue by Hamza-Talibi** [clouder-community/clouder#212]
Hello,
When I am trying to create a base, I get this error in Backup Services field on Backup notebook:
ValueError: Invalid field u'role_ids.name' in leaf "<osv.ExtendedLeaf: (u'role_ids.name', u'=', u'backup') on clouder_application_type (ctx: )>"
Could you help me?
Thanks.

**Comment by YannickB** [comment]
You're right, looks like a bug appears when we change the name of the fields. Shall be ok now.

**Comment by Hamza-Talibi** [comment]
Thank you so much.
It works now.
