### ISSUE TITLE
can't find odoo application in clouder master

### ISSUE THREAD

**Issue by Hamza-Talibi** [clouder-community/clouder#216]
Hello,
After installing the last version of clouder, I don't find applications like odoo, postgres.
Should I install it manually or there is a problem in installation?

**Comment by YannickB** [comment]
Hello,

Did you installed the module clouder_template_odoo ? It shall install application and dependencies like postgres.

**Comment by Hamza-Talibi** [comment]
I forget to install this module.
Thank you so much
Do you have a demo for a clouder master like the previous version?

**Comment by YannickB** [comment]
Unfortunately not right now, we will set one up when possible

**Comment by Hamza-Talibi** [comment]
Ok, thank you so much
