### ISSUE TITLE
Error : Incompatible ssh server (no acceptable macs)

### ISSUE THREAD

**Issue by ygol** [clouder-community/clouder#22]
Error on testing connection to new server.

it seem it is related to 
https://github.com/paramiko/paramiko/issues/526

any idea for a work around? TIA

================================
Odoo Warning
	
Connect error!

We were not able to connect to your server. Please make sure you add the public key in the authorized_keys file of your root user on your server.
If you were trying to connect to a container, a click on the 'reset key' button on the container record may resolve the problem.
Target : ns30.eu
Error : Incompatible ssh server (no acceptable macs)

**Comment by YannickB** [comment]
Hello,

First time we have this problem unfortunately I have no real suggestions to resolve it. Looking at the ticket you linked it seems to be a problem between paramiko and sshd config, not related to Clouder itself, I think the solution shall be in the discussions of the ticket.

**Comment by ygol** [comment]
ok. For reference; here's the link to the main discussion about the problem:
https://github.com/paramiko/paramiko/pull/356

**Comment by ygol** [comment]
so this problem is caused by the server?
I've installed Debian 7.5 (Wheezy).

or better try to fix the client side (orchestrator)?

**Comment by remydev** [comment]
it's work for me if i add in the file /etc/ssh/sshd_config

Ciphers aes128-ctr,aes192-ctr,aes256-ctr
MACs hmac-sha2-256,hmac-sha2-512

**Comment by YannickB** [comment]
Can we close this ticket?

**Comment by remydev** [comment]
I'm not the best qualified, but I think it's a problem of paramiko.
So the best way is to specify an official environment in order to deploy clouder and provide a support.
We can close this issue

**Comment by YannickB** [comment]
Ok I close it, don't hesitate to reopen if needed.

**Comment by romanki** [comment]
Hi, 
sorry for asking in closed issue.
But is it possible to resolve issue from client side but not server side (in sshd_config) ?

**Comment by vsns7861** [comment]
pip install --upgrade paramiko

**Comment by vsns7861** [comment]
It will work :)
