### ISSUE TITLE
 img_backup_bup missing package 

### ISSUE THREAD

**Issue by ErrafayM** [clouder-community/clouder#24]
I was having an issue yesterday building an image for "img_backup_bup" adding the g++ package fixed it . 

RUN DEBIAN_FRONTEND=noninteractive apt-get -y -q install python2.7-dev python-fuse python-pyxattr python-pylibacl python-tornado linux-libc-dev acl attr par2 git make cron ncftp g++

**Comment by YannickB** [comment]
Thank you, I also had the problem with a new installation

**Comment by YannickB** [comment]
Woups you're right, should be ok now
