### ISSUE TITLE
Error: Bug in img_postgres

### ISSUE THREAD

**Issue by MarcEtienneDery** [clouder-community/clouder#25]
There is a bug in the Postgres image. Since Postgres as updated to 9.4, the path use in the Dockerfile are now incorrect, resulting in an error during the build.

**Comment by YannickB** [comment]
Agree, I had the problem during the day. No time to update now but I'll correct it asap

**Comment by YannickB** [comment]
I made the change. This was probably the last change I make directly, I'll probably start to use the same procedure than the OCA, make PR and then ask for two review before merging it.
