### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [clouder-community/clouder#41]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:

* clouder_template_odoo/clouder_template_odoo_data.xml

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by Yenthe666** [comment]
Good catch :+1:

**Comment by YannickB** [comment]
Ok thank you for the notice, we shall correct the link asap
