### ISSUE TITLE
Use an SSH client to access the docker server with the Clouder instance

### ISSUE THREAD

**Issue by collex100** [clouder-community/clouder#47]
Use an SSH client to access the docker server with the Clouder instance (Web based SSH - Add SSH button in Clouder). Wishing for improving.

**Comment by YannickB** [comment]
Very good idea, indeed a ssh terminal directly in the clouder interface will be very handy. We could also execute in it the commands launched by clouder so we can see the effect in live.

**Comment by YannickB** [comment]
Closing all ticket which concern feature we are not working on currently. Still something we want to do whenever possible.
