### ISSUE TITLE
Nginx problem when creating base , doesnt redirect to the instance 

### ISSUE THREAD

**Issue by collex100** [clouder-community/clouder#49]
Nginx problem when creating base , doesnt redirect to the instance.  Add a script to migrate settings from the Nginx container into the Nginx Docker server(Solution nginx)

**Comment by YannickB** [comment]
Can you be more explicit regarding what you suggest here?

**Comment by collex100** [comment]
I can say on this issue next. After deployment base application does not start. https://github.com/ErrafayM recommend me to do the following (it was the same problem that he decided this way):

Yeah this is another problem that i had it myself too with nginx i had to install it manually in the docker server to make it work
apt-get install nginx
then get into your nginx container
docker exec -it www-panda1-nginx su
cat /etc/nginx/sites-available/www.panda1.pandaplus.biz and copy everything in there
and paste it in /etc/nginx/sites-available/default in your docker server
then finally
service nginx restart or /etc/init.d/nginx restart

That helped. This is all the information that I know on this issue.

**Comment by YannickB** [comment]
What I have trouble to understand is why you have two installations of nginx, you have one on one container and one on the hosting server, am I right?

**Comment by collex100** [comment]
Yes. Without this application does not start. Such a decision could run the application.

**Comment by YannickB** [comment]
But why do you have an nginx on your hosting server? Clouder shall take care to install and configure the nginx in the container

**Comment by collex100** [comment]
Probably, yeah. But it is not working. I shared the problem and me gave this advice, and worked.

**Comment by AyoubZahid** [comment]
Hello guys,

I work with https://github.com/ErrafayM, and this solution worked when we used localhost as a domain name, but when we used our registred domain neither the normal procedure specified in the doc of clouder nor this solution worked.

I also don't understand the need of nginx in the host server, maybe we did something wrong when configuring Clouder, or the nginx container is not well configured.

**Comment by YannickB** [comment]
I'm closing the ticket, please reopen if needed.
