### ISSUE TITLE
Hard coded ip in bind application

### ISSUE THREAD

**Issue by YannickB** [clouder-community/clouder#54]
I forgot a hardcoded value in https://github.com/clouder-community/clouder/blob/8.0/clouder_template_bind/clouder_template_bind.py#L61, it's the allow-transfer config with the ip of your dns provider.
Either we can allow transfer to every ip, or we use a option to specify the ip in the container configuration.

**Comment by pasgou** [comment]
Perhaps nothing should be hardcoded to make Clouder usable without changing the python itself.

That's the sense of my 2 pull requests for postfix, too

**Comment by YannickB** [comment]
yeah totally agree of course, I forgot this I'll try to correct it asap. I saw your PR for postfix, I need to add some correction to make it work but it will be merged

**Comment by pasgou** [comment]
Thanks

Cordialement

Pascal GOUHIER
Expert-Comptable

COPAGEX
Société d'expertise comptable
Membre de la Communauté des Experts en Gestion
8 Boulevard Albert Einstein
Parc de la Rivière
44300 NANTES

T : 02 40 58 56 49 <tel:02%2040%2058%2056%2049>
F : 02 40 95 11 81 <tel:02%2040%2095%2011%2081>

http://www.copagex.fr <http://www.copagex.fr/>
http://outils.copagex.fr <http://outils.copagex.fr/>

**Comment by YannickB** [comment]
Closing
