### ISSUE TITLE
New server added, but registry impossible to create

### ISSUE THREAD

**Issue by pasgou** [clouder-community/clouder#68]
This is the message i obtain when trying to create a registry container on a new server (my first one) :
"Connect error!

We were not able to connect to your server. Please make sure you add the public key in the authorized_keys file of your root user on your server.
If you were trying to connect to a container, a click on the 'reset key' button on the container record may resolve the problem.
Target : 149.202.38.100
Error : [Errno 111] Connection refused"

What public key is it asking for? the one in the server object in clouder OR the one of the server with clouder on it? In the second case, which public key must to be use (which user's key)?

I have an other question : where can we find the complete requirements to use clouder on the clouder server and on the managed server.

**Comment by ErrafayM** [comment]
It is asking if you added your SSH key in your root/.ssh/authorized_keys in the target 149.202.38.100 which will host your Docker images & containers, have you done this step? 

Follow the documentation 

https://doc.goclouder.net/en/latest/

**Comment by pasgou** [comment]
Thanks
Yes I did it. I follow this guide.

**Comment by ErrafayM** [comment]
Yes; the SSH Public KEY

**Comment by pasgou** [comment]
Yes.
What I did exactly : 
- a VPS (OVH) with Odoo/Clouder (Odoo from OCB git project, Clouder from its git project)
- a VPS (OVH) with ssh and docker installed


On the second VPS, my own ssh pub key to connect with my term AND the pub key which appear on the clouder page. After that, "enregistrer" the server. 
It creates all the folders and files on the clouder server, the key is in the file where it has to be.
To test, "test connection" does not respond anything (the code does not say it has to do something if it's well done). I tried without having send the key, and an alert appear, which give me the confirmation that connection is made between servers (what I had tried with ssh in the console).
But, when i try to create the registry container, as in the getting started guide, it returns me the given alert.

Did I miss something?

**Comment by ErrafayM** [comment]
Can you tell me if you're using debian or Ubuntu? because i had similar problem with Debian, and had to manually install sudo in my server. see #67 
If your problem has nothing to do with sudo, check your odoo logs.

**Comment by pasgou** [comment]
I use UBUNTU
When I test the connection : 
"2015-12-08 19:09:09,685 8224 INFO clouder openerp.addons.clouder.clouder_model: connect: ssh vpsxxxxxxxx.net
2015-12-08 19:09:11,335 8224 INFO ? paramiko.transport: Connected (version 2.0, client OpenSSH_6.6.1p1)
2015-12-08 19:09:11,445 8224 INFO ? paramiko.transport: Authentication (publickey) successful!"


After that, errors seem to come from an image of my service ... 

Voir mon blog joint à ce mail.
[log_odoo.txt](https://github.com/clouder-community/clouder/files/55944/log_odoo.txt)

I continue to search this way but it seems not to be the same bug as the "sudo" one in your report.

**Comment by pasgou** [comment]
What i found : 
- Docker wasn't install on my server (which is a VM called 'VPS Cloud' by OVH, my supplier)
- I installed Docker right now and : docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b901d36b6f2f: Pull complete 
0a6ba66e537a: Pull complete 
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest
Error response from daemon: Cannot start container 8686e3b6432537119002d63f76068745f0ca56527e72df1d65d496f2a012463b: failed to create endpoint thirsty_poincare on network bridge: failed to add the host (veth67a6c60) <=> sandbox (veth88ef18d) pair interfaces: operation not supported

I suppose that my VM, on which I couldn't install linux-image-extra, isn't compatible at all with Docker.
Did you have a similar experience?

**Comment by ErrafayM** [comment]
No , i have installed docker on a VPS by OVH too , works great.

**Comment by pasgou** [comment]
Question : Which version of VPS do you use? 2014 or 2016? cloud or classic?

**Comment by pasgou** [comment]
I found 
[this](https://www.ovh.com/fr/g1708.optimiser_lhebergement_dun_site_wordpress_sur_un_vps_grace_a_docker)
and 
[this](http://www.pierre-galvez.fr/Installer-Docker-sur-un-serveur-OVH/)
It seems to me that OVH is the problem.

**Comment by ErrafayM** [comment]
Cloud version

**Comment by ErrafayM** [comment]
Can you mail me? m.errafay123@gmail.com

**Comment by ErrafayM** [comment]
Have you fixed this issue?

**Comment by AyoubZahid** [comment]
There is a problem with docker in OVH Server, ( a dns problem).
when you try to build the registry, docker try to pull the registry from docker site, and it can't resolve the dns and it gives a dns error, clouder doesn't tell you about that unless you check the odoo-sever log.

i did  [this](http://soryy.com/blog/2014/docker-resolving-dns-issues-on-ovh/) and it worked.

Rebuild the registry img after that.

**Comment by pasgou** [comment]
I have réinstall 2 new VPS, tested for docker but not for clouder yet 

I ll tell you tomorrow 

In the same I prepared a script to install the first clouder server 

Envoyé de mon iPhone

**Comment by pasgou** [comment]
With a VPS 2016, docker works well, and I can see the clouder's action with "docker events" on the remote server.

Is it normal that the creation of www-registry take a long (very long) time?

I have a problem with the configuration of Apache on my Clouder server. How do you configure Apache (or NGINX) to work with odoo v8? I configured Apache to work with OpenErp v6.1 a long time ago, but it doesn't work with odoo 8.

Find my little contrib : 
- my script to configure the clouder server from scratch on a Ubuntu 14.04 LTS (but we have to work on apache section)
[odoo_install.sh.txt](https://github.com/clouder-community/clouder/files/60280/odoo_install.sh.txt)

- my script to install python 2.7.11
[update_python.sh.txt](https://github.com/clouder-community/clouder/files/60281/update_python.sh.txt)
