### ISSUE TITLE
[8.0] Awesome work! Would the modules in 8.0 by considered 'stable' for production?

### ISSUE THREAD

**Issue by lukebranch** [clouder-community/clouder#7]
@YannickB ,

Thank you for your awesome work on this set of modules, and for keeping it OpenSource! This will be an incredible time-saver for me and i'm sure for many others with similar needs.

This is more of a question than an issue, however I wasn't sure where else to ask it. Would you consider the 8.0 branch of Clouder to be stable enough to be put into production?

I am about to setup my company's Odoo hosting infrastructure and I think Clouder is the tool I will use to do this. I'll start working with Clouder on a development instance first to test out the features before putting it into production, but I would be interested to know whether you think the project's modules (outside the __unfinished__ folder) are production-ready, or whether this software should still be considered in alpha.

**Comment by YannickB** [comment]
Hello and thank you,

Today Clouder is used to managed at least two infrastructures, and everythings works well. What I can say is the fact that's this is as far as I can go alone,  that I am satisfied and that there is no more big refactoring planned.

But of course there is a lot of room for debug and improvement, until I have enough feedback I guess we can consider it as beta, but the kind of beta you can use in production. Please try to use it and if you need help ask your questions on the mailing-list, this is the only way we have to go forward now.

**Comment by lukebranch** [comment]
@YannickB ,

Thanks for letting me know. I'll definitely be using this in new implementations and i'll open issues if I run into any problems.

I've just joined the mailing list as well.
