### ISSUE TITLE
new server error in test connection

### ISSUE THREAD

**Issue by lvalenzu** [clouder-community/clouder#75]
Hello:

I created two machines in Amazon:

1. server1: Odoo 8 with  Clouder modules (ubuntu 14.04)
2. server2: debian server with openssh and docker (debian 8)
3. in Clouder (server1) create a new server
4. in server2 enable root user and add public key server created in point 3 (Connection port 22)
5. run "test connection" and get the error

Connect error!

We were not able to connect to your server. Please make sure you add the public key in the authorized_keys file of your root user on your server.
If you were trying to connect to a container, a click on the 'reset key' button on the container record may resolve the problem.
Target : clouder.odoo.cl
Error : [Errno 110] Connection timed out

6. In server2 I have only open port 22, requires some other open port?

regards

**Comment by lvalenzu** [comment]
update:

reviewing Clouder configuration files, I noticed that the file /opt/odoo/.ssh/config, had configured the port 14002, which was originally definition, to change it to port 22 gives me the following error

Connect error!

We were not able to connect to your server. Please make sure you add the public key in the authorized_keys file of your root user on your server.
If you were trying to connect to a container, a click on the 'reset key' button on the container record may resolve the problem.
Target : clouder.odoo.cl
Error : Incompatible ssh peer (no acceptable kex algorithm)

The version paramiko (1.10.1), in server odoo with clouder modules

what version of debian is recommended?, i install version 8

regards

**Comment by pasgou** [comment]
You have to upgrade paramiko to 1.16
pip install --upgrade paramiko

see my github odoo_install repository.
I propose a script to install odoo and clouder from zero. In it, you will find all dependencies.

**Comment by lvalenzu** [comment]
thanks pasgou,

upgrade paramiko and work

which is the repository referred github?

regards

**Comment by pasgou** [comment]
https://github.com/pasgou/odoo_install

**Comment by lvalenzu** [comment]
thanks

regards
