### ISSUE TITLE
How do you configure your e-mailing in Odoo

### ISSUE THREAD

**Issue by pasgou** [clouder-community/clouder#79]
I wonder if someone could explain me how to configure e-mailing in Odoo for the real life.
Could I explain what I use now and what I would like to have?

I have my domain name which I use for e-mail (hosting in Google for work with my domain name). I want to use it for my corporate website and for an Odoo instance (which will be the same server in fact).
Our mails are personal for each employee in my little company. I created 'mailing list' to have aliases for some services (paie@mydomain.fr, for example, to receive payroll elements).
But this strategy isn't good because i m afraid to loose some communications with clients or loose time to search archives when an employee goes aways or is seek.

In the same time, I can have some conversation that must kept confidential.

How do you proceed, why and technicaly speaking how works the e-mailing platform in Odoo?

All what I read in doc is too abstract, what I need is some examples on how it's work.

**Comment by YannickB** [comment]
I think you should ask this question in odoo or OCA forum to have a more complete answer.

Still I can share my experience for mailing list : it was a bad idea, no anti-spam feature. Personnally I yet didn't really install the mail features in Odoo for my customers (except for sending email, but not managing them). Again, I think you'll find in odoo forum more complete experience from users.

**Comment by pasgou** [comment]
Thanks

I will search in the jungle of the forum if I can find something. One idea : if you configure the smtp server in Odoo to be, for example, Mailjet, the anti spam functionality is transferred to this provider, isn’t it?

What I don’t know is how to be certain to have all exchanges between my employees and my clients, because of the damn habit.

**Comment by YannickB** [comment]
Closing old tickets
